version: "3"

services:
  node0:
    container_name: node0
    build: .
    image: "cosmossdk/simd"
    environment:
      - DEBUG=1
      - ID=0
      - LOG=${LOG:-dosumentserviced.log}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
      - "2345:2345"
    volumes:
      - ./nodecluster/node0:/home/container/.documentservice
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  node1:
    container_name: node1
    build: .
    # image: "cosmossdk/simd"
    environment:
      - DEBUG=1
      - ID=1
      - LOG=${LOG:-dosumentserviced.log}
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
      - "2346:2345"
    volumes:
      - ./nodecluster/node1:/home/container/.documentservice
    networks:
      localnet:
        ipv4_address: 192.168.10.3
  
  node2:
    container_name: node2
    build: .
    # image: "cosmossdk/simd"
    environment:
      - DEBUG=1
      - ID=2
      - LOG=${LOG:-dosumentserviced.log}
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
      - "2348:2345"
    volumes:
      - ./nodecluster/node2:/home/container/.documentservice
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  server:
    image: "hide101/documentservice_server"
    depends_on:
      - postgre
    restart: unless-stopped
    ports:
    - '5000:5000'
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    networks:
      localnet:
        ipv4_address: 192.168.10.10

  postgre:
    image: postgres:14.3
    environment:
      POSTGRES_DB: "document_service"
      POSTGRES_USER: "db_admin"
      POSTGRES_PASSWORD: "123456"
      PGDATA: "/var/lib/pgsql/data"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    networks:
      localnet:
        ipv4_address: 192.168.10.11
  
  client:
    image: "hide101/documentservice_client"
    restart: unless-stopped
    ports:
    - '3000:3000'
    logging:
      driver: "json-file"
      options:
        max-size: 100m
    networks:
      localnet:
        ipv4_address: 192.168.10.12
  

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/25